stages:
  - dependencies-core
  - dependencies-io
  - dependencies-CLHEP
  - dependencies-geant4
  - build

before_script:
  - yum -y install cmake glibc-devel which
  - set +e && source CI/setup_lcg.sh; set -e

variables:
  CMAKE_BASE_ARGS: -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install
  GIT_SUBMODULE_STRATEGY: recursive

geomodelcore-build:
  stage: dependencies-core
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/GeoModelDev/GeoModelCore.git
    - mkdir build_GeoModelCore
    - cd  build_GeoModelCore
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../GeoModelCore
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - install

geomodelio-build:
  stage: dependencies-io
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/GeoModelDev/GeoModelIO.git
    - mkdir build_GeoModelIO
    - cd build_GeoModelIO
    - cmake -DCMAKE_INSTALL_PREFIX=../install  ../GeoModelIO
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - install

CLHEP-build:
  stage: dependencies-CLHEP
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/CLHEP/CLHEP.git
    - cd CLHEP
    - git checkout CLHEP_2_4_1_0
    - cd ../ ; mkdir build_CLHEP
    - cd build_CLHEP
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../CLHEP
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - install


geant4-build:
  stage: dependencies-geant4
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/geant4/geant4.git
    - mkdir build_geant4
    - cd build_geant4
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../geant4 -DGEANT4_INSTALL_DATA=ON -DGEANT4_USE_GDML=ON -DGEANT4_BUILD_MULTITHREADED=ON -DXERCESC_ROOT_DIR=../../install/xerces-c
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
     - install


.build_template: &build_template
  stage: build
  tags:
    - cvmfs
  script:
    - echo "PWD; LS"
    - pwd; ls
    - mkdir build
    - cd build
    - echo "${CMAKE_ARGS}"
    - cmake ${CMAKE_ARGS}  ..
    - cmake --build . -- -j$(nproc)
    - cmake --build . -- install

build_slc6:
  <<: *build_template
  image: cern/slc6-base
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}

build_cc7:
  <<: *build_template
  image: cern/cc7-base
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
