# List of the CI build stages.
stages:
  - step-A
  - step-B
  - step-C

# List global variables
variables:
  CMAKE_DEPS_BASE_ARGS: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install
  CMAKE_BASE_ARGS: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install
  XERCESC_VERSION_BASE: 3.2.2
  # also, 'CMAKE_EXTRA_FLAGS' will be specified by specific jobs when needed, and used by job templates like 'geomodel-job'
  GIT_SUBMODULE_STRATEGY: recursive


# TEMPLATES FOR BUILDING ON DIFFERENT PLATFORMS
.macos-template-job: &macos-job
  tags:
    - macos
  rules:
    - if: '$CI_PROJECT_ROOT_NAMESPACE == "GeoModelDev"'
  allow_failure: true
  timeout: 30 minutes


.ubuntu-template-job-base: &ubuntu-job-base
  image: ubuntu:18.04
  tags:
    - docker

# NOTE
# The Ubuntu package 'nlohmann-json-dev' is version 2.x, too old for us.
# Thus, for GeoModelVisualization (GMEX), we now build nlohmann_json as part
# of the build, by using the 'standalone' job only
.ubuntu-template-job-default: &ubuntu-job
  <<: *ubuntu-job-base
  before_script:
    - apt-get update -qq && apt-get install -y -qq git wget unzip build-essential freeglut3-dev libboost-all-dev qt5-default mercurial libeigen3-dev libsqlite3-dev
    - wget https://cmake.org/files/v3.14/cmake-3.14.7-Linux-x86_64.tar.gz
    - tar -C /usr/local --strip-components=1 --no-same-owner -xvf cmake-*-Linux-x86_64.tar.gz
    - rm cmake-*-Linux-x86_64.tar.gz


# .ubuntu-template-job-registry: &ubuntu-job-registry
#   image: gitlab-registry.cern.ch/mbandier/geant4-ubuntu/base-image:1.1
#   tags:
#     - docker
#   before_script:
#     - apt-get update -qq && apt-get install -y -qq libeigen3-dev libsqlite3-dev


# TEMPLATES FOR BUILDING PACKAGES

.coin-build-template: &coin-job
  stage: step-A
  variables:
    CMAKE_ARGS: ${CMAKE_DEPS_BASE_ARGS}
  script:
    - pwd; ls
    #- wget https://bitbucket.org/Coin3D/coin/downloads/coin-4.0.0-src.zip
    - wget https://atlas-vp1.web.cern.ch/atlas-vp1/sources/coin-4.0.0-src.zip
    - unzip coin-4.0.0-src.zip -d coin-sources
    - mv coin-sources/* coin
    - mkdir build_coin
    - cd build_coin
    - cmake ${CMAKE_ARGS} ../coin
    - make -j2
    - make install
  artifacts:
    paths:
      - install

.soqt-build-template: &soqt-job
  stage: step-B
  variables:
    CMAKE_ARGS: ${CMAKE_DEPS_BASE_ARGS}
  script:
    - pwd; ls
    # - wget https://bitbucket.org/rmbianchi/soqt/downloads/soqt-1b4fe9d-macos-mojave-fix.zip
    # - unzip soqt-1b4fe9d-macos-mojave-fix.zip
    # - wget https://bitbucket.org/rmbianchi/soqt/get/CI-fix-25692a8.zip
    # - unzip CI-fix-25692a8.zip
    # - mv rmbianchi-soqt-25692a805a2c soqt
    #- hg clone https://rmbianchi@bitbucket.org/rmbianchi/soqt
    - wget https://atlas-vp1.web.cern.ch/atlas-vp1/sources/soqt.zip
    - unzip soqt.zip
    - mkdir build_soqt
    - cd build_soqt
    - echo "CMAKE_ARGS - ${CMAKE_ARGS}"
    - cmake ${CMAKE_ARGS} ../soqt
    - make -j2
    - make install
    - pwd; ls # CI debug only
    - ls ../ # CI debug only
    - ls ../../ # CI debug only
  artifacts:
    paths:
      - install


.xercesc-build-template-job: &xercesc-job
  stage: step-A
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
    XERCESC_VERSION: ${XERCESC_VERSION_BASE}
  script:
    - pwd; ls
    - wget https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-${XERCES_VERSION}.tar.gz
    - tar -xf xerces-c-${XERCES_VERSION}.tar.gz
    - mkdir xerces-c-build-${XERCES_VERSION}
    - cd xerces-c-build-${XERCES_VERSION}
    - cmake ${CMAKE_ARGS} ../xerces-c-${XERCEX_VERSION}
    - make -j4
    - make install
  artifacts:
    paths:
      - install


.geant4-build-template-job: &geant4-job
  stage: step-B
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/geant4/geant4.git
    - cd geant4
    - git checkout tags/v10.6.0
    - cd ../
    - mkdir Geant4-build
    - cd Geant4-build
    - cmake ${CMAKE_ARGS} -DGEANT4_INSTALL_DATA=ON -DGEANT4_USE_GDML=ON -DGEANT4_BUILD_MULTITHREADED=ON -DXERCESC_ROOT_DIR=../install/xerces-c/ ../geant4 -DGEANT4_USE_SYSTEM_EXPAT=OFF
    - make -j4
    - make install
  artifacts:
    paths:
      - install




.geomodel-build-template: &geomodel-job
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
  script:
    - echo "PWD; LS" # CI debug only
    - pwd; ls # CI debug only
    - ls ../ # CI debug only
    - ls ../../ # CI debug only
    - cmake --version # CI debug only
    - mkdir build
    - cd build
    - echo "CMAKE_ARGS - ${CMAKE_ARGS}"
    - cmake ${CMAKE_ARGS} ${CMAKE_EXTRA_FLAGS} .. # the CMAKE_EXTRA_FLAGS are set by specific jobs when needed
    - cmake --build . -- -j2
    - cmake --build . -- install
    - pwd; ls # CI debug only
    - ls ../ # CI debug only
    - ls ../../ # CI debug only
  artifacts:
    paths:
      - install



# ACTUAL BUILD JOBS

## a debug job
debug-job:
  stage: step-A
  script:
    - echo "CI_REPOSITORY_URL -- $CI_REPOSITORY_URL"
    - echo "GITLAB_USER_NAME -- $GITLAB_USER_NAME"
    - echo "GITLAB_USER_LOGIN -- $GITLAB_USER_LOGIN"
    - echo "CI_PROJECT_URL -- $CI_PROJECT_URL"
    - echo "CI_PROJECT_NAMESPACE -- $CI_PROJECT_NAMESPACE"
    - echo "CI_PROJECT_ROOT_NAMESPACE -- $CI_PROJECT_ROOT_NAMESPACE"
    - echo "CI_PROJECT_PATH -- $CI_PROJECT_PATH"
  when: manual


### MACOS BUILD JOBS
mac-coin:
  <<: *macos-job
  <<: *coin-job

mac-soqt:
  <<: *macos-job
  <<: *soqt-job
  needs: ["mac-coin"]
  before_script:
    - export PATH="/usr/local/opt/qt/bin:$PATH" # to make Qt5 discoverable by CMake

mac-geomodel-base:
  <<: *macos-job
  <<: *geomodel-job
  stage: step-A
  before_script:
    - brew install nlohmann-json xerces-c
  after_script:
    - brew remove --ignore-dependencies nlohmann-json xerces-c

mac-geomodel-visualization:
  <<: *macos-job
  <<: *geomodel-job
  stage: step-C
  needs: ["mac-coin", "mac-soqt"]
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
    CMAKE_EXTRA_FLAGS: -DGEOMODEL_BUILD_VISUALIZATION=TRUE
  before_script:
    - brew install nlohmann-json xerces-c
    - export PATH="/usr/local/opt/qt/bin:$PATH" # to make Qt5 discoverable by CMake
  after_script:
    - brew remove --ignore-dependencies nlohmann-json xerces-c



### UBUNTU BUILD JOBS
ubu-coin:
  <<: *ubuntu-job
  <<: *coin-job

ubu-soqt:
  <<: *ubuntu-job
  <<: *soqt-job
  needs: ["ubu-coin"]

ubu-gm-base-builtin:
  <<: *ubuntu-job
  <<: *geomodel-job
  stage: step-A
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
    CMAKE_EXTRA_FLAGS: -DGEOMODEL_USE_BUILTIN_JSON=TRUE -DGEOMODEL_USE_BUILTIN_XERCESC=TRUE


ubu-gm-visualization-builtin:
  <<: *ubuntu-job
  <<: *geomodel-job
  needs: ["ubu-coin", "ubu-soqt"]
  stage: step-C
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
    CMAKE_CONFIG_FLAGS: -DGEOMODEL_BUILD_VISUALIZATION=TRUE
    CMAKE_EXTRA_FLAGS: -DGEOMODEL_USE_BUILTIN_JSON=TRUE -DGEOMODEL_USE_BUILTIN_XERCESC=TRUE

ubu-gm-examples-builtin:
  <<: *ubuntu-job
  <<: *geomodel-job
  stage: step-A
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
    CMAKE_CONFIG_FLAGS: -DGEOMODEL_BUILD_EXAMPLES=TRUE
    CMAKE_EXTRA_FLAGS:  -DGEOMODEL_USE_BUILTIN_JSON=TRUE -DGEOMODEL_USE_BUILTIN_XERCESC=TRUE


ubu-XercesC:
  <<: *ubuntu-job
  <<: *xercesc-job

ubu-XercesC-323:
  <<: *ubuntu-job
  <<: *xercesc-job
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
    XERCESC_VERSION: 3.2.3

ubu-geant4:
  <<: *ubuntu-job
  <<: *geant4-job
  needs: ["ubu-XercesC"]


ubu-gm-examples-gmg4-builtinjson:
  <<: *ubuntu-job
  <<: *geomodel-job
  stage: step-C
  needs: ["ubu-geant4", "ubu-XercesC"]
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
    CMAKE_CONFIG_FLAGS: -DGEOMODEL_BUILD_EXAMPLES_W_GEANT4=TRUE
    CMAKE_EXTRA_FLAGS: -DGEOMODEL_USE_BUILTIN_JSON=TRUE

ubu-gm-gmg4-builtinjson:
  <<: *ubuntu-job
  <<: *geomodel-job
  stage: step-C
  needs: ["ubu-geant4", "ubu-XercesC"]
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
    CMAKE_CONFIG_FLAGS: -DGEOMODEL_BUILD_GEOMODELG4=TRUE
    CMAKE_EXTRA_FLAGS: -DGEOMODEL_USE_BUILTIN_JSON=TRUE

ubu-gm-fullsimlight-builtinjson:
  <<: *ubuntu-job
  <<: *geomodel-job
  stage: step-C
  needs: ["ubu-geant4", "ubu-XercesC"]
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
    CMAKE_CONFIG_FLAGS: -DGEOMODEL_BUILD_FULLSIMLIGHT=TRUE
    CMAKE_EXTRA_FLAGS: -DGEOMODEL_USE_BUILTIN_JSON=TRUE


### Documentation

docs-build:
    stage: step-A
    rules:
      - changes:
        - documentation/**/*
    image: gitlab-registry.cern.ch/authoring/documentation/mkdocs:stable
    before_script:
        - pip install markdown-include
        - pip install mkdocs-git-revision-date-plugin # See: https://github.com/mkdocs/mkdocs/issues/1408#issuecomment-443592097
    script:
        #- git --version #TODO: update the docker image to have git
        - ls
        - cd documentation
        - ls
        - mkdocs build --clean --site-dir public
        - ls
        - cp .htaccess public/papers/internal/
        - ls
    artifacts:
        paths:
            - documentation/public
        expire_in: 1 hour

docs-deploy:
    stage: step-B
    needs: ["docs-build"]
    rules:
      - changes:
        - documentation/**/*
    variables:
      "EOS_PATH": "/eos/project/g/geomodel/www/home"
    image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
    #only:
    #    - master
    script:
        - ls
        - cd documentation
        - ls
        - deploy-eos

