stages:
  - dependencies
  - build

before_script:
  - yum -y install cmake glibc-devel which
  - set +e && source CI/setup_lcg.sh; set -e

variables:
  CMAKE_BASE_ARGS: -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install
  GIT_SUBMODULE_STRATEGY: recursive

geomodelcore-build:
  stage: dependencies
  script:
    - git clone https://gitlab.cern.ch/GeoModelDev/GeoModelCore.git
    - mkdir geomodelcore-build geomodelcore-install
    - cmake -DCMAKE_INSTALL_PREFIX=../install -Bgeomodelcore-build -HGeoModelCore
    - make -j$(nproc) -C geomodelcore-build
    - make -C geomodelcore-build install
    
    
.build_template: &build_template
  stage: build
  tags: 
    - cvmfs
  script:
    - mkdir build
    - cd build
    - echo "${CMAKE_ARGS}"
    - cmake ${CMAKE_ARGS}  ..
    - cmake --build . -- -j$(nproc)
    - cmake --build . -- install

build_slc6:
  <<: *build_template
  image: cern/slc6-base
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}

build_cc7:
  <<: *build_template
  image: cern/cc7-base
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
