# Copyright (C) 2002-2019 CERN for the benefit of the ATLAS collaboration
#
# GitLab CI configuration for this repository.
#

# image: ubuntu:18.04
image: atlas/centos7-atlasos:latest

variables:
  CMAKE_BASE_ARGS: -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install
  GIT_SUBMODULE_STRATEGY: recursive

# List all the build stages.
stages:
  - dependencies-coin
  - dependencies-soqt
  - dependencies-core
  - dependencies-io
  - build


coin-build:
  stage: dependencies-coin
  script:
    - pwd; ls
    - wget https://bitbucket.org/Coin3D/coin/downloads/coin-4.0.0-src.zip
    - unzip coin-4.0.0-src.zip -d coin-sources
    - mv coin-sources/* coin
    - mkdir build_coin
    - cd build_coin
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../coin
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - install


soqt-build:
  stage: dependencies-soqt
  script:
    - pwd; ls
    - wget https://bitbucket.org/rmbianchi/soqt/downloads/soqt-1b4fe9d-macos-mojave-fix.zip
    - unzip soqt-1b4fe9d-macos-mojave-fix.zip
    - mkdir build_soqt
    - cd build_soqt
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../soqt
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - install


geomodelcore-build:
  stage: dependencies-core
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/GeoModelDev/GeoModelCore.git
    - mkdir geomodelcore-build
    - cd geomodelcore-build
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../GeoModelCore
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - install


geomodelio-build:
  stage: dependencies-io
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/GeoModelDev/GeoModelIO.git
    - mkdir geomodelio-build
    - cd geomodelio-build
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../GeoModelIO
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - install



.build_template: &build_template
  stage: build
  tags:
    - cvmfs
  script:
    - echo "PWD; LS"
    - pwd; ls
    - mkdir build
    - cd build
    - echo "${CMAKE_ARGS}"
    - cmake ${CMAKE_ARGS}  ..
    - cmake --build . -- -j$(nproc)
    - cmake --build . -- install

build_new:
  <<: *build_template
#   image: cern/slc6-base
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}

# build_slc6:
#   <<: *build_template
#   image: cern/slc6-base
#   variables:
#     CMAKE_ARGS: ${CMAKE_BASE_ARGS}

# build_cc7:
#   <<: *build_template
#   image: cern/cc7-base
#   variables:
#     CMAKE_ARGS: ${CMAKE_BASE_ARGS}
