stages:
  - deps-geomodelcore
  - deps-CLHEP
  - deps-xerces-c
  - deps-Geant4
  - build


variables:
  CMAKE_BASE_ARGS: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install
  GIT_SUBMODULE_STRATEGY: recursive


# TEMPLATES FOR BUILDING ON DIFFERENT PLATFORMS
.macos-template-job: &macos-job
  tags:
    - macos-geomodeldev
  allow_failure: true
  timeout: 60 minutes
  before_script:
    - export PATH="/usr/local/opt/qt/bin:$PATH" # to make Qt5 discoverable by CMake

.ubuntu-template-job: &ubuntu-job
  image: gitlab-registry.cern.ch/mbandier/geant4-ubuntu/base-image:latest
  tags:
    - docker

.geomodelcore-build-template-job: &geomodelcore-job
  stage: deps-geomodelcore
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/GeoModelDev/GeoModelCore.git
    - mkdir geomodelcore-build
    - cd geomodelcore-build
    - cmake ${CMAKE_ARGS} ../GeoModelCore
    - make -j32
    - make install
  artifacts:
    paths:
      - install

.CLHEP-build-template-job: &CLHEP-job
  stage: deps-CLHEP
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/CLHEP/CLHEP.git
    - cd CLHEP
    - git checkout CLHEP_2_4_1_0
    - cd ../
    - mkdir CLHEP-build
    - cd CLHEP-build
    - cmake ${CMAKE_ARGS} ../CLHEP
    - make -j32
    - make install
  artifacts:
    paths:
      - install

.xerces-c-build-template-job: &xerces-c-job
  stage: deps-xerces-c
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
  script:
    - pwd; ls
    - wget https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-3.2.2.tar.gz
    - tar -xf xerces-c-3.2.2.tar.gz
    - mkdir xerces-c-build
    - cd xerces-c-build
    - cmake ${CMAKE_ARGS} ../xerces-c-3.2.2
    - make -j32
    - make install
  artifacts:
    paths:
      - install


.Geant4-build-template-job: &Geant4-job
  stage: deps-Geant4
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/geant4/geant4.git
    - cd geant4
    - git checkout tags/v10.6.0
    - cd ../
    - mkdir Geant4-build
    - cd Geant4-build
    - cmake ${CMAKE_ARGS} -DGEANT4_INSTALL_DATA=ON -DGEANT4_USE_GDML=ON -DGEANT4_BUILD_MULTITHREADED=ON -DXERCESC_ROOT_DIR=../install/xerces-c/ ../geant4
    - make -j32
    - make install
  artifacts:
    paths:
      - install

.geomodelg4-build-template: &geomodelg4-job
  stage: build
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/GeoModelDev/GeoModelG4.git
    - mkdir GeoModelG4-build
    - cd GeoModelG4-build
    - cmake ${CMAKE_ARGS} ../GeoModelG4
    - make -j32
    - make install
  artifacts:
    paths:
      - install

# ACTUAL JOBS

### MACOS PATH
geomodelcore-mac:
  <<: *macos-job
  <<: *geomodelcore-job

CLHEP-mac:
  <<: *macos-job
  <<: *CLHEP-job

xerces-c-mac:
  <<: *macos-job
  <<: *xerces-c-job

Geant4-mac:
  <<: *macos-job
  <<: *Geant4-job
  needs: ["CLHEP-mac", "xerces-c-mac"]

geomodelg4-mac:
  <<: *macos-job
  <<: *geomodelg4-job
  needs: ["geomodelcore-mac", "CLHEP-mac", "Geant4-mac"]


### UBUNTU PATH
geomodelcore-ubuntu:
  <<: *ubuntu-job
  <<: *geomodelcore-job

#CLHEP-ubuntu:
#  <<: *ubuntu-job
#  <<: *CLHEP-job

#geomodelio-ubuntu:
#  <<: *ubuntu-job
#  <<: *geomodelio-job
#  needs: ["geomodelcore-ubuntu"]

# xerces-c-ubuntu:
#   <<: *ubuntu-job
#   <<: *xerces-c-job

# Geant4-ubuntu:
#   <<: *ubuntu-job
#   <<: *Geant4-job
#   needs: ["CLHEP-ubuntu", "xerces-c-ubuntu"]

geomodelg4-ubuntu:
  <<: *ubuntu-job
  <<: *geomodelg4-job
  needs: ["geomodelcore-ubuntu"]
