stages:
  - dependencies-coin
  - dependencies-soqt
  - dependencies-core
  - dependencies-io
  - build

before_script:
  - yum -y install cmake glibc-devel freeglut-devel which
#   - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
#   - source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
#   - asetup none,gcc8,cmakesetup
  #- set +e && source CI/setup_lcg.sh; set -e

variables:
  CMAKE_BASE_ARGS: -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install
  GIT_SUBMODULE_STRATEGY: recursive


coin-build:
  stage: dependencies-coin
  script:
    - pwd; ls
    - wget https://bitbucket.org/Coin3D/coin/downloads/coin-4.0.0-src.zip
    - unzip coin-4.0.0-src.zip -d coin-sources
    - mv coin-sources/* coin
    - mkdir build_coin
    - cd build_coin
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../coin
    - make -j$(nproc)
    - make install
  artifacts: 
    paths:
      - install
      
      
soqt-build:
  stage: dependencies-soqt
  script:
    - pwd; ls
    - wget https://bitbucket.org/rmbianchi/soqt/downloads/soqt-1b4fe9d-macos-mojave-fix.zip
    - unzip soqt-1b4fe9d-macos-mojave-fix.zip
    - mkdir build_soqt
    - cd build_soqt
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../soqt
    - make -j$(nproc)
    - make install
  artifacts: 
    paths:
      - install
      
      
geomodelcore-build:
  stage: dependencies-core
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/GeoModelDev/GeoModelCore.git
    - mkdir geomodelcore-build
    - cd geomodelcore-build
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../GeoModelCore
    - make -j$(nproc)
    - make install
  artifacts: 
    paths:
      - install
      

geomodelio-build:
  stage: dependencies-io
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/GeoModelDev/GeoModelIO.git
    - mkdir geomodelio-build
    - cd geomodelio-build
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../GeoModelIO
    - make -j$(nproc)
    - make install
  artifacts: 
    paths:
      - install
    
    
    
.build_template: &build_template
  stage: build
  tags: 
    - cvmfs
  script:
    - echo "PWD; LS"
    - pwd; ls
    - mkdir build
    - cd build
    - echo "${CMAKE_ARGS}"
    - cmake ${CMAKE_ARGS}  ..
    - cmake --build . -- -j$(nproc)
    - cmake --build . -- install

build_slc6:
  <<: *build_template
  image: cern/slc6-base
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}

build_cc7:
  <<: *build_template
  image: cern/cc7-base
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
